### ISSUE TITLE
errors don't show up in gutters

### ISSUE THREAD

**Issue by laureljanej** [Thomas-Lebeau/SublimeLinter-contrib-bootlint#1]
Errors aren't showing up in the gutters of the sublime interface.  I've got the paths set for bootlint and can see errors and line numbers in the console if I put the linter in debug mode.  But if I run the command for "show all errors" I get a message that says "No lint errors." and no outlines/warnings show up in my code or in the gutters. I've been through all of the Sublime Linter troubleshooting docs and I can't find anything that would be causing this...

**Comment by pkishino** [comment]
same problem

**Comment by pkishino** [comment]
ok, found problem. bootlint has changed the message..Ill make a pr and submit
